-- 021_transaction_seq — cost basis must not depend on row order (P0-4).
--
-- Both money folds ordered by (trade_date, created_at). Neither column breaks a
-- tie between transactions booked on the same day:
--
--   * `created_at` defaults to now(), which is transaction_timestamp() — constant
--     for a whole transaction. A CSV import writes every row inside one
--     BEGIN/COMMIT, so every imported row shares one timestamp exactly.
--   * `id` is gen_random_uuid(), which recovers nothing.
--
-- Verified against this database: three rows inserted in one transaction
-- produced ONE distinct created_at. The sort key ties completely, and Postgres
-- is then free to return them in any order.
--
-- The consequence is not academic. Buy 10@100, buy 10@200, sell 10, all on one
-- date:
--
--   insertion order (buy, buy, sell) -> qty 10, cost 1500  (avg 150)
--   sell folded first                -> qty 10, cost 3000  (avg 300)
--
-- because the sell branch computes `avg = p.qty.isZero() ? 0 : cost/qty`, so a
-- sell seen before its buys relieves nothing. recomputeDerivedState DELETEs and
-- re-INSERTs positions, so the persisted avg_cost can change between two runs
-- over identical data, with no gap declared. It feeds every unrealized gain the
-- user sees.
--
-- `seq` is a monotonic insertion counter: the order rows were actually written.
-- For an import that is the broker's own chronology, which is the correct fold
-- order. A back-dated transaction added later sorts last within its trade_date;
-- under average-cost accounting that is the intended reading — the fold is
-- "what did I know, in the order I recorded it" — and it is at least stable and
-- reproducible, which the previous behaviour was not.

ALTER TABLE transactions ADD COLUMN seq bigint;

-- Backfill deterministically rather than in physical order, so existing rows get
-- a sensible sequence instead of whatever the heap happens to return.
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY trade_date, created_at, id) AS rn
    FROM transactions
)
UPDATE transactions t SET seq = o.rn FROM ordered o WHERE t.id = o.id;

ALTER TABLE transactions ALTER COLUMN seq SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(
  pg_get_serial_sequence('transactions', 'seq'),
  COALESCE((SELECT MAX(seq) FROM transactions), 0) + 1,
  false
);

-- The fold's exact access path: one portfolio, ordered by (trade_date, seq).
-- Supersedes transactions_portfolio_idx, whose leading columns it shares.
DROP INDEX IF EXISTS transactions_portfolio_idx;
CREATE INDEX transactions_fold_idx ON transactions (portfolio_id, trade_date, seq);

COMMENT ON COLUMN transactions.seq IS
  'Monotonic insertion order. Tie-breaks the money fold within a trade_date, where created_at is constant across a transaction and id is random (P0-4).';
